### ISSUE TITLE
TeX environment recommendation for windows users

### ISSUE THREAD

**Issue by zxybazh** [taineleau/Fudan_PRML2017_Assignment#1]
There is one very recommended TeX environment IDE on windows called *WinEdt*. You may want to mention it in your assignment0 guide for reference. You can check out [Here](http://www.winedt.com/).

**Comment by taineleau-zz** [comment]
Could you submit a PR on this? Thanks for your feedback.

**Comment by zxybazh** [comment]
PR submitted.
